"""User-facing Romanian copy shared by the bot and link-account function."""

TEXTS = {
    "report_private_only": "Te rog folosește /raporteaza într-o conversație privată cu botul.",
    "report_subtype_apa": "💧 Apă",
    "report_subtype_gaz": "🔥 Gaz",
    "report_subtype_electricitate": "⚡ Electricitate",
    "report_calendar_months": (
        "ianuarie", "februarie", "martie", "aprilie", "mai", "iunie",
        "iulie", "august", "septembrie", "octombrie", "noiembrie", "decembrie",
    ),
    "report_calendar_weekdays": ("Lu", "Ma", "Mi", "Jo", "Vi", "Sâ", "Du"),
    "report_calendar_empty_cell": "·",
    "report_calendar_cancel": "Anulează",
    "login_private_only": "Te rog folosește /login într-o conversație privată cu botul.",
    "login_page_unconfigured": "Pagina de autentificare nu este configurată încă. Încearcă din nou mai târziu.",
    "login_created": "Deschide butonul de mai jos pentru a conecta contul. Linkul expiră în 10 minute.",
    "login_failed": "Nu am putut crea linkul acum. Încearcă din nou mai târziu.",
    "login_button": "🔐 Autentificare",
    "logout_private_only": "Te rog folosește /logout într-o conversație privată cu botul.",
    "logout_not_linked": "Nu există un cont conectat la acest chat.",
    "logout_done": "Contul Telegram a fost deconectat.",
    "logout_failed": "Nu am putut deconecta contul acum. Încearcă din nou mai târziu.",
    "link_success": "✅ Contul tău a fost conectat cu succes.",
    "report_login_required": "Pentru a trimite o raportare, conectează mai întâi contul cu /login.",
    "report_blocked": (
        "Nu poți raporta până pe {date}: raportările tale au primit prea multe răspunsuri "
        "„Nu, la mine funcționează”."
    ),
    "report_choose_subtype": "Ce problemă vrei să raportezi?",
    "report_choose_timing": "Problema este activă acum sau urmează să înceapă?",
    "report_live": "🔴 Se întâmplă acum",
    "report_live_selected": "Ai ales să raportezi o problemă activă acum.",
    "report_upcoming": "📅 Urmează",
    "report_choose_date": "Alege data începerii. Evenimentul va fi setat să înceapă la 09:00, ora Chișinăului.",
    "report_date_selected": "Data aleasă: {date}.",
    "report_choose_location": "Trimite locația problemei folosind butonul de mai jos. Raportarea va fi creată după primirea locației.",
    "report_location_button": "📍 Trimite locația",
    "report_cancel_button": "❌ Anulează",
    "report_cancelled": "Raportarea a fost anulată.",
    "report_invalid_location": "Nu am primit o locație. Apasă butonul „Trimite locația” sau /cancel pentru a opri raportarea.",
    "report_invalid_date": "Alege o dată viitoare din calendar.",
    "report_created": "✅ Raportarea a fost trimisă. Va deveni vizibilă public după confirmarea vecinilor.",
    "report_create_failed": "Nu am putut salva raportarea acum. Încearcă din nou mai târziu.",
    "report_invalid_choice": "Alegerea nu este validă. Te rog selectează una dintre opțiuni.",
}
